language: php

dist: bionic

php:
   - 7.3

services:
    - mysql

before_script:
  - cp .env.example .env

  - mysql -e "create database laravel"

  - composer self-update

  - composer install --no-progress --no-suggest --no-interaction --optimize-autoloader

  - php artisan key:generate

  - npm install
  
  - npm rebuild node-sass
  
  - npm run production
  
  - php artisan migrate --seed
  
  - ./vendor/laravel/dusk/bin/chromedriver-linux &

  - php artisan serve > /dev/null 2>&1 &
  
script:

  - vendor/bin/phpunit

  - php artisan dusk